### ISSUE TITLE
Min width on buttons necessary?

### ISSUE THREAD

**Issue by ammapspeople** [MapsIndoors/css#1]
@marksdk For buttons with very short text or just an icon, content is misaligned due to a minimum width of `xxx-large`. Could we remove that minimum width without any consequenses?

**Comment by markhougaard** [comment]
@ammapspeople You tell me :) I think it makes sense to not have a min-width, but I'm not sure what, if anything, will break if there's no min-width.

Could you show me an example of what it looks like with just an icon, or one character in the button?

**Comment by ammapspeople** [comment]
@marksdk 

Here with min-width:
![image](https://user-images.githubusercontent.com/50314165/75321915-14ff1980-5872-11ea-9b47-96cee5a8181f.png)

Here without min-width:
![image](https://user-images.githubusercontent.com/50314165/75321964-2ea06100-5872-11ea-8efc-e56a50e93e91.png)

I think we could just remove it.

**Comment by ammapspeople** [comment]
Or: make sure content is centered.

**Comment by markhougaard** [comment]
Yup, agree. Just remove it.

**Comment by ammapspeople** [comment]
Resolved in 0.0.3
